name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.4'
    - run: go build -v
    - uses: actions/upload-artifact@v2
      with:
        name: bmc_exporter
        path: bmc_exporter
