name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bazel
      env:
        BAZEL_VERSION: 3.7.0
        BAZEL_SHA256: 621089dc4d396612603a55f18f55acded29d9b21534ebaa99406a0b4b05029fb
      run: |
        curl -sSLo install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
        echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
        chmod +x install.sh
        ./install.sh --user
        rm -f install.sh
    - run: bazel build //:archive
    - run: bazel run //:bmc_exporter -- --version
    - uses: actions/upload-artifact@v2
      with:
        name: archive
        path: bazel-bin/archive.tar.gz
